### ISSUE TITLE
I can't use the vue devtools in vscode-devtools

### ISSUE THREAD

**Issue by CG-man** [CodeMooseUS/vscode-devtools#11]
vscode: 
![image](https://user-images.githubusercontent.com/12809498/48932332-41710b00-ef36-11e8-8874-bf4a1f22de06.png)
chrome devtools:
![image](https://user-images.githubusercontent.com/12809498/48932348-5d74ac80-ef36-11e8-8ba5-a1028bb2fa23.png)

**Comment by CodeMooseUS** [comment]
Unfortunately all chrome browser extensions are managed by the chrome browser itself, and can't be used by the stand alone devtools I'm using for vscode. This means that the Vue devtools extension won't show up in the vscode devtools.

I don't know of a good way to fix this without changes to chrome itself so I don't think I'll be able to fix this any time soon.

**Comment by FatehAK** [comment]
Same goes for React Dev tools too I guess. I came across this [link](https://discuss.atom.io/t/solved-unable-to-load-react-devtools-in-a-webview/42607) maybe its possible to add?

**Comment by minkir014** [comment]
You can set it as your new release aim. I have an idea you can make the extension understands Vue as HTML and open it in another window. I think this wouldn't be hard.

**Comment by minkir014** [comment]
Is someone here?

**Comment by CodeMooseUS** [comment]
Sorry, I haven't had a whole lot of time to look into this (or in general). I think you would need to modify the extensions in order for them to no longer require content scripts since they aren't available over CDP. 

Work to enumerate the extensions and actually load them would also need to be done since this isn't going to be provided when not running directly in the browser.

To be clear, the devtools used here are the chrome devtools frontend ones available via npm. This isn't running the full embedded browser ones like electron and chrome use as there is no way to do that currently.

It would probably be easier to just create a standalone react/Vue extension for vscode rather than trying to add it here.

Is there some special integration that the extensions do with the other parts of the devtools that would be lacking in a standalone vscode ext?

**Comment by TheLarkInn** [comment]
@CodeMooseUS In fact, the Vue Team has already created a standalone Vue DevTools that works in Electron or can be hosted (if you review the architecture). I'm not sure the React Extension is setup the same way however. 

https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md
