### ISSUE TITLE
Support other chromium browsers

### ISSUE THREAD

**Issue by ChildishGiant** [CodeMooseUS/vscode-devtools#15]
At the moment both attaching a target and launching as debugger only work on chrome. If the command's running is `chrome.exe --disable-extensions --remote-debugging-port=9222` like the docs state, would it be possible to point it to another chromium exe?

**Comment by mavanmanen** [comment]
This would be great, I use Vivaldi, another popular browser also running on chromium.

**Comment by CodeMooseUS** [comment]
This should be possible with the current version.

### Launch
You should be able to specify the exe you would like to load via the VSCode setting:
```vscode-devtools-for-chrome.chromePath```
Which can be found under File -> Preferences -> Settings -> Extensions -> DevTools For Chrome -> Chrome path

For example: 
(JSON) - ```"vscode-devtools-for-chrome.chromePath": "C:\\Program Files (x86)\\BraveSoftware\\Brave-Browser\\Application\\brave.exe""```
(UI) -
![image](https://user-images.githubusercontent.com/12698640/54406935-4ac6e480-4699-11e9-9ac2-05f8e7be42a8.png)

Now when you use the devtools launch config it should start your specified browser instead of chrome. (Remember to not have chrome open using the same remote debugging port)

### Attach
The extension works by looking for a chrome debugging protocol websocket endpoint on the 
 hostname/port specified in the settings (by default localhost:9222).
So if you manually launch a chromium based browser with remote debugging enabled on that port it should automatically find its pages when you use the attach command.

For example:
Manually start brave via the command line ```"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --remote-debugging-port=9222```

Now when you run the ```DevTools for Chrome: Attach to a target``` command, it should list the tabs you have open in brave.
(Remember to not have any other browsers open using the same remote debugging port)


Let me know if that works for you and I can add it to the readme.
