### ISSUE TITLE
Chrome browser extensions seem to cause the webview to crash

### ISSUE THREAD

**Issue by CodeMooseUS** [CodeMooseUS/vscode-devtools#4]
If you try to attach to an instance of chrome that is using extensions (I was seeing it with ad block plus) then the embedded webview seems to crash and show a black window.

The workaround is to launch chrome with the --disable-extensions flag to turn them off

**Comment by codeunifier** [comment]
The problem with this method is that if you already have an instance of chrome running with extensions, running chrome.exe with the --disable-extensions flag doesn't actually disable extensions. Not sure why. The Debugger for Chrome extension that has become the standard is able to launch chrome without extensions. I feel like that default standard should be the same for this extension. There shouldn't be a workaround to this issue. A user like myself who uses Chrome as their main browser is unable to use this extension, because I have to close my active browser in order to launch without extensions.
